//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_EMAIL_REMINDER
    {
        public decimal PROPOSAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_KOMTEK_ID { get; set; }
        public string PROPOSAL_JUDUL_PNPS { get; set; }
        public string PROPOSAL_RUANG_LINGKUP { get; set; }
        public decimal KOMTEK_ID { get; set; }
        public string KOMTEK_CODE { get; set; }
        public string KOMTEK_NAME { get; set; }
        public string KOMTEK_EMAIL { get; set; }
        public Nullable<decimal> APPROVAL_ID { get; set; }
        public Nullable<decimal> APPROVAL_PROPOSAL_ID { get; set; }
        public string APPROVAL_DATE { get; set; }
        public Nullable<decimal> USIA_HARI { get; set; }
    }
}
