//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_VW_UPDATE_SNI
    {
        public decimal PROPOSAL_REV_ID { get; set; }
        public Nullable<decimal> PROPOSAL_REV_PROPOSAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_REV_MERIVISI_ID { get; set; }
        public Nullable<decimal> SNI_ID_UPDATE { get; set; }
        public string SNI_NOMOR_UPDATE { get; set; }
        public Nullable<decimal> SNI_TIDAK_BERLAKU_UPDATE { get; set; }
        public Nullable<System.DateTime> SNI_PUBLISH_START_DATE_UPDATE { get; set; }
        public Nullable<decimal> PROPOSAL_JENIS_PERUMUSAN_UPD { get; set; }
        public Nullable<System.DateTime> SNI_PUBLISH_END_DATE_UPDATE { get; set; }
        public Nullable<decimal> PROPOSAL_ID_UPDATE { get; set; }
        public Nullable<decimal> SNI_ID { get; set; }
        public Nullable<decimal> PROPOSAL_ID { get; set; }
        public Nullable<decimal> SNI_PROPOSAL_ID { get; set; }
        public string SNI_NOMOR { get; set; }
        public string SNI_JUDUL { get; set; }
        public Nullable<decimal> SNI_STATUS { get; set; }
        public string SNI_JUDUL_ENG { get; set; }
        public Nullable<decimal> SNI_IS_PUBLISH { get; set; }
        public Nullable<System.DateTime> SNI_PUBLISH_START_DATE { get; set; }
        public Nullable<System.DateTime> SNI_PUBLISH_END_DATE { get; set; }
        public Nullable<decimal> SNI_TIDAK_BERLAKU { get; set; }
        public string PROPOSAL_PNPS_CODE { get; set; }
        public string KOMTEK_CODE { get; set; }
        public string KOMTEK_NAME { get; set; }
        public Nullable<decimal> PROPOSAL_JENIS_PERUMUSAN { get; set; }
        public Nullable<System.DateTime> SNI_CREATE_DATE { get; set; }
        public Nullable<decimal> UMUR_UPDATE { get; set; }
        public Nullable<decimal> UMUR_BULAN_UPDATE { get; set; }
        public Nullable<decimal> UMUR_TAHUN_UPDATE { get; set; }
    }
}
