//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_BIBLIOGRAFI
    {
        public decimal BIBLIOGRAFI_ID { get; set; }
        public string BIBLIOGRAFI_JUDUL { get; set; }
        public Nullable<decimal> BIBLIOGRAFI_CREATE_BY { get; set; }
        public Nullable<System.DateTime> BIBLIOGRAFI_CREATE_DATE { get; set; }
        public Nullable<decimal> BIBLIOGRAFI_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> BIBLIOGRAFI_UPDATE_DATE { get; set; }
        public Nullable<decimal> BIBLIOGRAFI_STATUS { get; set; }
        public string BIBLIOGRAFI_LOGCODE { get; set; }
    }
}
