//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_TAS_EDUCATION
    {
        public decimal TAS_EDUCATION_ID { get; set; }
        public Nullable<decimal> TAS_EDUCATION_TAS_ID { get; set; }
        public string TAS_EDUCATION_INSTITUSI { get; set; }
        public string TAS_EDUCATION_YEAR { get; set; }
        public string TAS_EDUCATION_PRODI { get; set; }
        public Nullable<decimal> TAS_EDUCATION_STATUS { get; set; }
    }
}
