//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_SNI_STYLE
    {
        public decimal SNI_STYLE_ID { get; set; }
        public string SNI_STYLE_NAME { get; set; }
        public string SNI_STYLE_VALUE { get; set; }
        public Nullable<decimal> SNI_STYLE_SORT { get; set; }
        public Nullable<decimal> SNI_STYLE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SNI_STYLE_CREATE_DATE { get; set; }
        public Nullable<decimal> SNI_STYLE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> SNI_STYLE_UPDATE_DATE { get; set; }
        public Nullable<decimal> SNI_STYLE_STATUS { get; set; }
    }
}
