//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_TAS_RIWAYAT
    {
        public decimal TAS_RIWAYAT_ID { get; set; }
        public Nullable<decimal> TAS_RIWAYAT_TAS_ID { get; set; }
        public Nullable<decimal> TAS_RIWAYAT_TYPE { get; set; }
        public string TAS_RIWAYAT_INSTITUSI_NAME { get; set; }
        public string TAS_RIWAYAT_TAHUN { get; set; }
        public string TAS_RIWAYAT_BIDANG_JABATAN { get; set; }
        public string TAS_RIWAYAT_JENIS_PELATIHAN { get; set; }
        public string TAS_RIWAYAT_PENYELENGGARA { get; set; }
        public string TAS_RIWAYAT_PENGALAMAN { get; set; }
        public Nullable<decimal> TAS_RIWAYAT_STATUS { get; set; }
    }
}
