//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_SCOPE
    {
        public decimal SCOPE_ID { get; set; }
        public string SCOPE_CODE { get; set; }
        public string SCOPE_NAME { get; set; }
        public Nullable<decimal> SCOPE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SCOPE_CREATE_DATE { get; set; }
        public Nullable<decimal> SCOPE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> SCOPE_UPDATE_DATE { get; set; }
        public Nullable<decimal> SCOPE_STATUS { get; set; }
    }
}
