//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_DOC_REFERENCES
    {
        public decimal DOCREF_ID { get; set; }
        public Nullable<decimal> DOCREF_DATA_ID { get; set; }
        public string DOCREF_DATA_CODE { get; set; }
        public Nullable<decimal> DOCREF_GROUP { get; set; }
        public string DOCREF_DATA_NAME { get; set; }
        public Nullable<decimal> DOCREF_CREATE_BY { get; set; }
        public Nullable<System.DateTime> DOCREF_CREATE_DATE { get; set; }
        public Nullable<decimal> DOCREF_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DOCREF_UPDATE_DATE { get; set; }
        public Nullable<decimal> DOCREF_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> DOCREF_APPROVE_DATE { get; set; }
        public Nullable<decimal> DOCREF_STATUS { get; set; }
        public string DOCREF_LOG_CODE { get; set; }
        public Nullable<decimal> DOCREF_CANCUSTOM { get; set; }
    }
}
