//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_ACUAN_NON_SNI
    {
        public decimal ACUAN_NON_SNI_ID { get; set; }
        public string ACUAN_NON_SNI_TYPE { get; set; }
        public string ACUAN_NON_SNI_NO_STANDAR { get; set; }
        public string ACUAN_NON_SNI_JUDUL { get; set; }
        public Nullable<decimal> ACUAN_NON_SNI_CREATE_BY { get; set; }
        public Nullable<System.DateTime> ACUAN_NON_SNI_CREATE_DATE { get; set; }
        public Nullable<decimal> ACUAN_NON_SNI_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> ACUAN_NON_SNI_UPDATE_DATE { get; set; }
        public Nullable<decimal> ACUAN_NON_SNI_STATUS { get; set; }
        public string ACUAN_NON_SNI_LOGCODE { get; set; }
    }
}
