//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_LOGBOOK
    {
        public decimal LOGBOOK_ID { get; set; }
        public string LOGBOOK_NOMOR { get; set; }
        public Nullable<decimal> LOGBOOK_PROPOSAL_ID { get; set; }
        public string LOGBOOK_FORBIDDEN_NOMOR { get; set; }
    }
}
