//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_REFERENCES
    {
        public decimal REF_ID { get; set; }
        public Nullable<decimal> REF_TYPE { get; set; }
        public string REF_CODE { get; set; }
        public string REF_NAME { get; set; }
        public Nullable<decimal> REF_CREATE_BY { get; set; }
        public Nullable<System.DateTime> REF_CREATE_DATE { get; set; }
        public Nullable<decimal> REF_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> REF_UPDATE_DATE { get; set; }
        public Nullable<decimal> REF_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> REF_APPROVE_DATE { get; set; }
        public Nullable<decimal> REF_STATUS { get; set; }
        public string REF_LOG_CODE { get; set; }
    }
}
