//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_FILETYPES
    {
        public decimal FILETYPE_ID { get; set; }
        public string FILETYPE_FONTAWESOME_ICON { get; set; }
        public string FILETYPE_ENTYPO_ICON { get; set; }
        public string FILETYPE_GLYPH_ICON { get; set; }
        public string FILETYPE_EXT { get; set; }
        public string FILETYPE_NAME { get; set; }
        public Nullable<decimal> FILETYPE_STATUS { get; set; }
    }
}
