//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_BIDANG
    {
        public decimal BIDANG_ID { get; set; }
        public string BIDANG_CODE { get; set; }
        public string BIDANG_NAME { get; set; }
        public string BIDANG_SHORT_NAME { get; set; }
        public Nullable<decimal> BIDANG_CREATE_BY { get; set; }
        public Nullable<System.DateTime> BIDANG_CREATE_DATE { get; set; }
        public Nullable<decimal> BIDANG_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> BIDANG_UPDATE_DATE { get; set; }
        public Nullable<decimal> BIDANG_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> BIDANG_APPROVE_DATE { get; set; }
        public Nullable<decimal> BIDANG_STATUS { get; set; }
        public string BIDANG_LOG_CODE { get; set; }
    }
}
