//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_FOLDERS
    {
        public decimal FOLDER_ID { get; set; }
        public Nullable<decimal> FOLDER_CODE { get; set; }
        public Nullable<decimal> FOLDER_PARENT_ID { get; set; }
        public string FOLDER_NAME { get; set; }
        public Nullable<decimal> FOLDER_ALLOW_ADDFOLDER { get; set; }
        public Nullable<decimal> FOLDER_ALLOW_ADDFILE { get; set; }
        public Nullable<decimal> FOLDER_ACCESS_ID { get; set; }
        public Nullable<decimal> FOLDER_KOMTEK_ID { get; set; }
        public Nullable<decimal> FOLDER_USER_ID { get; set; }
        public string FOLDER_PASSWORD { get; set; }
        public string FOLDER_ICON { get; set; }
        public string FOLDER_ICON_COLOR { get; set; }
        public Nullable<decimal> FOLDER_IS_SHARED { get; set; }
        public Nullable<decimal> FOLDER_SORT { get; set; }
        public Nullable<decimal> FOLDER_CREATE_BY { get; set; }
        public Nullable<System.DateTime> FOLDER_CREATE_DATE { get; set; }
        public Nullable<decimal> FOLDER_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> FOLDER_UPDATE_DATE { get; set; }
        public Nullable<decimal> FOLDER_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> FOLDER_APPROVE_DATE { get; set; }
        public Nullable<decimal> FOLDER_STATUS { get; set; }
        public string FOLDER_LOG_CODE { get; set; }
    }
}
