//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTAL_PROFILE
    {
        public decimal PROFILE_ID { get; set; }
        public string PROFILE_TENTANG_KAMI { get; set; }
        public string PROFILE_KONTAK_KAMI { get; set; }
        public Nullable<System.DateTime> PROFILE_CREATE_DATE { get; set; }
        public Nullable<decimal> PROFILE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> PROFILE_UPDATE_DATE { get; set; }
        public Nullable<decimal> PROFILE_UPDATE_BY { get; set; }
        public Nullable<decimal> PROFILE_STATUS { get; set; }
    }
}
