//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTAL_SLIDER
    {
        public decimal SLIDER_ID { get; set; }
        public string SLIDER_JUDUL { get; set; }
        public string SLIDER_IMAGE_BIG_PATH { get; set; }
        public string SLIDER_IMAGE_SMALL_PATH { get; set; }
        public Nullable<decimal> SLIDER_IMAGE_IS_USE { get; set; }
        public Nullable<decimal> SLIDER_STATUS { get; set; }
        public string SLIDER_IMAGE_LINK { get; set; }
        public string SLIDER_IMAGE_BIG_LINK { get; set; }
        public string SLIDER_IMAGE_SMALL_LINK { get; set; }
    }
}
