//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CONFIG
    {
        public decimal CONFIG_ID { get; set; }
        public string CONFIG_NAME { get; set; }
        public string CONFIG_VALUE { get; set; }
        public Nullable<decimal> CONFIG_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CONFIG_UPDATE_DATE { get; set; }
        public string CONFIG_LOG_CODE { get; set; }
    }
}
