//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ACCESS_DETAIL
    {
        public decimal ACCESS_DETAIL_ID { get; set; }
        public Nullable<decimal> ACCESS_DETAIL_ACCESS_ID { get; set; }
        public Nullable<decimal> ACCESS_DETAIL_MENU_ID { get; set; }
        public Nullable<decimal> ACCESS_DETAIL_TYPE { get; set; }
        public Nullable<decimal> ACCESS_CREATE_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_DETAIL_CREATE_DATE { get; set; }
        public Nullable<decimal> ACCESS_DETAIL_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_DETAIL_UPDATE_DATE { get; set; }
        public Nullable<decimal> ACCESS_DETAIL_STATUS { get; set; }
        public string ACCESS_DETAIL_LOG_CODE { get; set; }
    }
}
