//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DOC_ACCESS_DETAIL_SELECT
    {
        public decimal DOC_ACCESS_DETAIL_ID { get; set; }
        public Nullable<decimal> DOC_ACCESS_DETAIL_ACCESS_ID { get; set; }
        public string SNI_STYLE_NAME { get; set; }
        public string SNI_STYLE_VALUE { get; set; }
        public Nullable<decimal> SNI_STYLE_SORT { get; set; }
        public Nullable<decimal> DOC_ACCESS_DETAIL_STYLE_STATUS { get; set; }
    }
}
