//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_EMAIL
    {
        public decimal EMAIL_ID { get; set; }
        public string EMAIL_NAME { get; set; }
        public string EMAIL_PASSWORD { get; set; }
        public Nullable<decimal> EMAIL_IS_USE { get; set; }
        public Nullable<System.DateTime> EMAIL_CREATE_DATE { get; set; }
        public Nullable<decimal> EMAIL_CREATE_BY { get; set; }
        public Nullable<System.DateTime> EMAIL_UPDATE_DATE { get; set; }
        public Nullable<decimal> EMAIL_UPDATE_BY { get; set; }
        public Nullable<decimal> EMAIL_STATUS { get; set; }
    }
}
