//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_HIT_COUNTERS
    {
        public decimal HC_ID { get; set; }
        public string HC_IP { get; set; }
        public string HC_LINK { get; set; }
        public string HC_USER_AGENT { get; set; }
        public Nullable<System.DateTime> HC_DATE { get; set; }
        public Nullable<decimal> HC_STATUS { get; set; }
    }
}
