//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER_INTERN
    {
        public decimal USER_INTERN_ID { get; set; }
        public string USER_INTERN_FULLNAME { get; set; }
        public string USER_INTERN_ADDRESS { get; set; }
        public string USER_INTERN_EMAIL { get; set; }
        public string USER_INTERN_PHONE { get; set; }
        public Nullable<long> USER_INTERN_CREATE_BY { get; set; }
        public Nullable<System.DateTime> USER_INTERN_CREATE_DATE { get; set; }
        public Nullable<long> USER_INTERN_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> USER_INTERN_UPDATE_DATE { get; set; }
        public Nullable<short> USER_INTERN_STATUS { get; set; }
        public string USER_INTERN_LOG_CODE { get; set; }
    }
}
