//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LINK
    {
        public decimal LINK_ID { get; set; }
        public string LINK_NAME { get; set; }
        public Nullable<decimal> LINK_IS_USE { get; set; }
        public Nullable<decimal> LINK_CREATE_BY { get; set; }
        public Nullable<System.DateTime> LINK_CREATE_DATE { get; set; }
        public Nullable<decimal> LINK_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LINK_UPDATE_DATE { get; set; }
        public Nullable<decimal> LINK_STATUS { get; set; }
    }
}
