//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER_PUBLIC
    {
        public decimal USER_PUBLIC_ID { get; set; }
        public string USER_PUBLIC_KTPSIM { get; set; }
        public string USER_PUBLIC_NAMA_LENGKAP { get; set; }
        public string USER_PUBLIC_EMAIL { get; set; }
        public string USER_PUBLIC_TELPON { get; set; }
        public Nullable<decimal> USER_PUBLIC_STAKEHOLDER { get; set; }
        public Nullable<decimal> USER_PUBLIC_PROVINSI_ID { get; set; }
        public Nullable<decimal> USER_PUBLIC_KOTAKAB_ID { get; set; }
        public Nullable<decimal> USER_PUBLIC_CREATE_BY { get; set; }
        public Nullable<System.DateTime> USER_PUBLIC_CREATE_DATE { get; set; }
        public Nullable<decimal> USER_PUBLIC_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> USER_PUBLIC_UPDATE_DATE { get; set; }
        public string USER_PUBLIC_TOKEN_KEY { get; set; }
        public string USER_PUBLIC_ACTIVATION_KEY { get; set; }
        public string USER_PUBLIC_LOG_CODE { get; set; }
        public Nullable<decimal> USER_PUBLIC_STATUS { get; set; }
        public string USER_PUBLIC_LINK_ACTIVATION { get; set; }
        public string USER_PUBLIC_NOKK { get; set; }
    }
}
