//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DOC_ACCESS_DETAIL
    {
        public decimal DOC_ACCESS_DETAIL_ID { get; set; }
        public Nullable<decimal> DOC_ACCESS_DETAIL_ACCESS_ID { get; set; }
        public Nullable<decimal> DOC_ACCESS_DETAIL_STYLE_ID { get; set; }
        public Nullable<decimal> DOC_ACCESS_DETAIL_STYLE_STATUS { get; set; }
        public Nullable<int> DOC_ACCESS_DETAIL_CREATE_BY { get; set; }
        public Nullable<System.DateTime> DOC_ACCESS_DETAIL_CREATE_DATE { get; set; }
        public Nullable<int> DOC_ACCESS_DETAIL_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DOC_ACCESS_DETAIL_UPDATE_DATE { get; set; }
    }
}
