//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MENU
    {
        public decimal MENU_ID { get; set; }
        public Nullable<decimal> MENU_PARENT_ID { get; set; }
        public string MENU_URL { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_ICON { get; set; }
        public string MENU_SORT { get; set; }
        public string MENU_POSITION { get; set; }
        public string MENU_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MENU_CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MENU_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MENU_UPDATE_DATE { get; set; }
        public Nullable<decimal> MENU_STATUS { get; set; }
        public string MENU_LOG_CODE { get; set; }
    }
}
