//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SNI_SK_SISNI
    {
        public decimal ID { get; set; }
        public string NOMOR_SNI { get; set; }
        public string NOMOR_SK { get; set; }
    }
}
