//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_PROPOSAL_APPROVAL
    {
        public decimal APPROVAL_ID { get; set; }
        public Nullable<decimal> APPROVAL_PROPOSAL_ID { get; set; }
        public Nullable<decimal> APPROVAL_TYPE { get; set; }
        public string APPROVAL_REASON { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
        public Nullable<decimal> APPROVAL_BY { get; set; }
        public Nullable<decimal> APPROVAL_STATUS_PROPOSAL { get; set; }
        public Nullable<decimal> APPROVAL_STATUS_SESSION { get; set; }
        public Nullable<decimal> APPROVAL_STATUS { get; set; }
    }
}
