//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_PROPOSAL_REV
    {
        public decimal PROPOSAL_REV_ID { get; set; }
        public Nullable<decimal> PROPOSAL_REV_PROPOSAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_REV_MERIVISI_ID { get; set; }
    }
}
