//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_MAINTENANCE_DETAILS
    {
        public decimal MAINTENANCE_DETAIL_ID { get; set; }
        public Nullable<decimal> MAINTENANCE_DETAIL_MTN_ID { get; set; }
        public Nullable<decimal> MAINTENANCE_DETAIL_SNI_ID { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_DETAIL_REV_DATE { get; set; }
        public Nullable<decimal> MAINTENANCE_DETAIL_RESULT { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_DETAIL_REPORT_DATE { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_DETAIL_USUL_DATE { get; set; }
    }
}
