//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DOCUMENTS
    {
        public decimal DOC_ID { get; set; }
        public string DOC_CODE { get; set; }
        public Nullable<decimal> DOC_FOLDER_ID { get; set; }
        public Nullable<decimal> DOC_RELATED_TYPE { get; set; }
        public Nullable<decimal> DOC_RELATED_ID { get; set; }
        public string DOC_NUMBER { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_DESCRIPTION { get; set; }
        public Nullable<decimal> DOC_REGULATOR { get; set; }
        public string DOC_INFO { get; set; }
        public string DOC_FILE_PATH { get; set; }
        public string DOC_FILE_NAME { get; set; }
        public string DOC_FILETYPE { get; set; }
        public string DOC_LINK { get; set; }
        public Nullable<decimal> DOC_EDITABLE { get; set; }
        public Nullable<decimal> DOC_CREATE_BY { get; set; }
        public Nullable<System.DateTime> DOC_CREATE_DATE { get; set; }
        public Nullable<decimal> DOC_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DOC_UPDATE_DATE { get; set; }
        public Nullable<decimal> DOC_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> DOC_APPROVE_DATE { get; set; }
        public Nullable<decimal> DOC_STATUS { get; set; }
        public string DOC_LOG_CODE { get; set; }
        public Nullable<decimal> DOC_CREATE_TYPE { get; set; }
        public Nullable<decimal> DOC_DELETABLE { get; set; }
        public Nullable<decimal> DOC_IS_XML { get; set; }
        public string DOC_XML_DATA { get; set; }
    }
}
