//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_LPK_SCOPE
    {
        public decimal LPK_SCOPE_ID { get; set; }
        public Nullable<decimal> LPK_SCOPE_LPK_ID { get; set; }
        public Nullable<decimal> LPK_SCOPE_SCOPE_ID { get; set; }
        public Nullable<decimal> LPK_SCOPE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> LPK_SCOPE_CREATE_DATE { get; set; }
        public Nullable<decimal> LPK_SCOPE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LPK_SCOPE_UPDATE_DATE { get; set; }
        public Nullable<decimal> LPK_SCOPE_STATUS { get; set; }
        public string LPK_SCOPE_LOGCODE { get; set; }
    }
}
