//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_TEST
    {
        public decimal TEST_TABLE { get; set; }
        public string TEST_NAME { get; set; }
        public Nullable<decimal> TEST_STATUS { get; set; }
    }
}
