//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_SNI
    {
        public decimal SNI_ID { get; set; }
        public Nullable<decimal> SNI_PROPOSAL_ID { get; set; }
        public Nullable<decimal> SNI_DOC_ID { get; set; }
        public Nullable<System.DateTime> SNI_CREATE_DATE { get; set; }
        public Nullable<decimal> SNI_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SNI_UPDATE_DATE { get; set; }
        public Nullable<decimal> SNI_UPDATE_BY { get; set; }
        public Nullable<decimal> SNI_STATUS { get; set; }
        public string SNI_NOMOR { get; set; }
        public string SNI_JUDUL { get; set; }
        public Nullable<decimal> SNI_SK_ID { get; set; }
        public Nullable<decimal> SNI_IS_PUBLISH { get; set; }
        public Nullable<System.DateTime> SNI_PUBLISH_START_DATE { get; set; }
        public Nullable<System.DateTime> SNI_PUBLISH_END_DATE { get; set; }
        public Nullable<decimal> SNI_TIDAK_BERLAKU { get; set; }
        public string SNI_JUDUL_ENG { get; set; }
    }
}
