//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_REGULASI_TEKNIS_DETAIL
    {
        public decimal RETEK_DETAIL_ID { get; set; }
        public Nullable<decimal> RETEK_DETAIL_RETEK_ID { get; set; }
        public Nullable<decimal> RETEK_DETAIL_SNI_ID { get; set; }
        public Nullable<decimal> RETEK_DETAIL_CREATE_BY { get; set; }
        public Nullable<System.DateTime> RETEK_DETAIL_CREATE_DATE { get; set; }
        public Nullable<decimal> RETEK_DETAIL_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> RETEK_DETAIL_UPDATE_DATE { get; set; }
        public Nullable<decimal> RETEK_DETAIL_STATUS { get; set; }
        public Nullable<decimal> RETEK_DETAIL_DOCUMENT_ID { get; set; }
    }
}
