//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_SK_PENETAPAN
    {
        public decimal PENETAPAN_ID { get; set; }
        public string PENETAPAN_NO_SK { get; set; }
        public Nullable<System.DateTime> TANGGAL_SK { get; set; }
        public string JUDUL_SK { get; set; }
        public string FILES { get; set; }
        public string SK_LOCATION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
    }
}
