//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_LPK_DETAIL_SNI
    {
        public decimal LPK_DETAIL_SNI_ID { get; set; }
        public Nullable<decimal> LPK_DETAIL_SNI_LPK_ID { get; set; }
        public Nullable<decimal> LPK_DETAIL_SNI_SNI_ID { get; set; }
        public Nullable<decimal> LPK_DETAIL_SNI_CREATE_BY { get; set; }
        public Nullable<System.DateTime> LPK_DETAIL_SNI_CREATE_DATE { get; set; }
        public Nullable<decimal> LPK_DETAIL_SNI_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LPK_DETAIL_SNI_UPDATE_DATE { get; set; }
        public Nullable<decimal> LPK_DETAIL_SNI_STATUS { get; set; }
        public string LPK_DETAIL_SNI_LOGCODE { get; set; }
    }
}
