//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_PROPOSAL_REFERENCE
    {
        public decimal PROPOSAL_REF_ID { get; set; }
        public Nullable<decimal> PROPOSAL_REF_PROPOSAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_REF_TYPE { get; set; }
        public Nullable<decimal> PROPOSAL_REF_SNI_ID { get; set; }
        public string PROPOSAL_REF_EXT_NOMOR { get; set; }
        public string PROPOSAL_REF_EXT_JUDUL { get; set; }
    }
}
