//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_LOG_JOB
    {
        public decimal ID { get; set; }
        public string KETERANGAN { get; set; }
        public Nullable<System.DateTime> INSERT_TIME { get; set; }
    }
}
