//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_PROPOSAL
    {
        public decimal PROPOSAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_TYPE { get; set; }
        public Nullable<decimal> PROPOSAL_YEAR { get; set; }
        public Nullable<decimal> PROPOSAL_KOMTEK_ID { get; set; }
        public string PROPOSAL_KONSEPTOR { get; set; }
        public string PROPOSAL_INSTITUSI { get; set; }
        public string PROPOSAL_TIM_NAMA { get; set; }
        public string PROPOSAL_TIM_ALAMAT { get; set; }
        public string PROPOSAL_TIM_PHONE { get; set; }
        public string PROPOSAL_TIM_EMAIL { get; set; }
        public string PROPOSAL_TIM_FAX { get; set; }
        public string PROPOSAL_NO_SNI_PROPOSAL { get; set; }
        public string PROPOSAL_JUDUL_SNI_PROPOSAL { get; set; }
        public string PROPOSAL_PNPS_CODE { get; set; }
        public string PROPOSAL_JUDUL_PNPS { get; set; }
        public string PROPOSAL_JUDUL_PNPS_ENG { get; set; }
        public string PROPOSAL_RUANG_LINGKUP { get; set; }
        public string PROPOSAL_RUANG_LINGKUP_ENG { get; set; }
        public Nullable<decimal> PROPOSAL_JENIS_PERUMUSAN { get; set; }
        public Nullable<decimal> PROPOSAL_JALUR { get; set; }
        public Nullable<decimal> PROPOSAL_JENIS_ADOPSI { get; set; }
        public Nullable<decimal> PROPOSAL_METODE_ADOPSI { get; set; }
        public Nullable<decimal> PROPOSAL_TERJEMAHAN_SNI_ID { get; set; }
        public Nullable<decimal> PROPOSAL_RALAT_SNI_ID { get; set; }
        public Nullable<decimal> PROPOSAL_AMD_SNI_ID { get; set; }
        public Nullable<decimal> PROPOSAL_IS_URGENT { get; set; }
        public string PROPOSAL_PASAL { get; set; }
        public Nullable<decimal> PROPOSAL_IS_HAK_PATEN { get; set; }
        public string PROPOSAL_IS_HAK_PATEN_DESC { get; set; }
        public string PROPOSAL_INFORMASI { get; set; }
        public string PROPOSAL_TUJUAN { get; set; }
        public string PROPOSAL_PROGRAM_PEMERINTAH { get; set; }
        public string PROPOSAL_PIHAK_BERKEPENTINGAN { get; set; }
        public string PROPOSAL_LAMPIRAN_FILE_PATH { get; set; }
        public Nullable<decimal> PROPOSAL_IS_ASSIGN_KOMTEK { get; set; }
        public Nullable<decimal> PROPOSAL_IS_POLLING { get; set; }
        public Nullable<decimal> PROPOSAL_POLLING_ID { get; set; }
        public Nullable<decimal> PROPOSAL_IS_BATAL { get; set; }
        public Nullable<decimal> PROPOSAL_CREATE_BY { get; set; }
        public Nullable<System.DateTime> PROPOSAL_CREATE_DATE { get; set; }
        public Nullable<decimal> PROPOSAL_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> PROPOSAL_UPDATE_DATE { get; set; }
        public Nullable<decimal> PROPOSAL_STATUS { get; set; }
        public Nullable<decimal> PROPOSAL_STATUS_PROSES { get; set; }
        public string PROPOSAL_LOG_CODE { get; set; }
        public Nullable<decimal> PROPOSAL_SNI_ID_OLD { get; set; }
        public string PROPOSAL_ICS_NAME { get; set; }
        public string PROPOSAL_KET_BATAL { get; set; }
        public string PROPOSAL_ABSTRAK { get; set; }
        public string PROPOSAL_ABSTRAK_ENG { get; set; }
        public string PROPOSAL_MANFAAT_PENERAPAN { get; set; }
        public Nullable<decimal> PROPOSAL_IS_ORG_MENDUKUNG { get; set; }
        public string PROPOSAL_DUKUNGAN_FILE_PATH { get; set; }
        public string PROPOSAL_IS_DUPLIKASI_DESC { get; set; }
        public string PROPOSAL_CODE { get; set; }
        public Nullable<decimal> PROPOSAL_TAS_ID { get; set; }
        public string PROPOSAL_BATAL_ATTACHMENT { get; set; }
        public Nullable<System.DateTime> PROPOSAL_TAS_DATE { get; set; }
        public Nullable<decimal> PROPOSAL_CLASIFICATION_ID { get; set; }
        public string PROPOSAL_NO_SURAT_PEMBATALAN { get; set; }
        public string PROPOSAL_RETEK_ID { get; set; }
        public string PROPOSAL_LPK_ID { get; set; }
        public string KLASIFIKASI_JNS_SNI { get; set; }
        public string PROPOSAL_HAK_PATEN_LOCATION { get; set; }
        public string PROPOSAL_HAK_PATEN_NAME { get; set; }
        public string MONITORING_NO_MEMO_KAPUS { get; set; }
        public string MONITORING_NO_MEMO_DEPUTI { get; set; }
    }
}
