//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_PROPOSAL_ADOPSI
    {
        public decimal PROPOSAL_ADOPSI_ID { get; set; }
        public Nullable<decimal> PROPOSAL_ADOPSI_PROPOSAL_ID { get; set; }
        public string PROPOSAL_ADOPSI_NOMOR_JUDUL { get; set; }
        public Nullable<decimal> PROPOSAL_ADOPSI_ACUAN_ID { get; set; }
        public Nullable<decimal> PROPOSAL_ADOPSI_TYPE { get; set; }
    }
}
