//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DOC_RELATEDS
    {
        public decimal DOCREL_ID { get; set; }
        public Nullable<decimal> DOCREL_DOC_ID { get; set; }
        public Nullable<decimal> DOCREL_DOC_REL_ID { get; set; }
        public Nullable<decimal> DOCREL_STATUS { get; set; }
    }
}
