//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_POLLING
    {
        public decimal POLLING_ID { get; set; }
        public Nullable<decimal> POLLING_PROPOSAL_ID { get; set; }
        public string POLLING_TYPE { get; set; }
        public Nullable<System.DateTime> POLLING_START_DATE { get; set; }
        public Nullable<System.DateTime> POLLING_END_DATE { get; set; }
        public Nullable<decimal> POLLING_VERSION { get; set; }
        public string POLLING_REASON { get; set; }
        public Nullable<decimal> POLLING_IS_KUORUM { get; set; }
        public Nullable<decimal> POLLING_JML_PARTISIPAN { get; set; }
        public Nullable<decimal> POLLING_SETUJU { get; set; }
        public Nullable<decimal> POLLING_SETUJU_PERSEN { get; set; }
        public Nullable<decimal> POLLING_TDK_SETUJU { get; set; }
        public Nullable<decimal> POLLING_TDK_SETUJU_PERSEN { get; set; }
        public Nullable<decimal> POLLING_ABSTAIN { get; set; }
        public Nullable<decimal> POLLING_ABSTAIN_PERSEN { get; set; }
        public Nullable<decimal> POLLING_CREATE_BY { get; set; }
        public Nullable<System.DateTime> POLLING_CREATE_DATE { get; set; }
        public Nullable<decimal> POLLING_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> POLLING_UPDATE_DATE { get; set; }
        public Nullable<decimal> POLLING_STATUS { get; set; }
        public Nullable<decimal> POLLING_LOGCODE { get; set; }
    }
}
