//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_SNI_DOC
    {
        public decimal SNI_DOC_ID { get; set; }
        public Nullable<decimal> SNI_DOC_PROPOSAL_ID { get; set; }
        public Nullable<decimal> SNI_DOC_TYPE { get; set; }
        public string SNI_DOC_FILE_PATH { get; set; }
        public Nullable<decimal> SNI_DOC_VERSION { get; set; }
        public Nullable<decimal> SNI_DOC_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SNI_DOC_CREATE_DATE { get; set; }
        public string SNI_DOC_LOG_CODE { get; set; }
        public Nullable<decimal> SNI_DOC_STATUS { get; set; }
    }
}
