//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_MAINTENANCES
    {
        public decimal MAINTENANCE_ID { get; set; }
        public string MAINTENANCE_DOC_NUMBER { get; set; }
        public Nullable<decimal> MAINTENANCE_REV_NUMBER { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_DATE { get; set; }
        public Nullable<decimal> MAINTENANCE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_CREATE_DATE { get; set; }
        public Nullable<decimal> MAINTENANCE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_UPDATE_DATE { get; set; }
        public Nullable<decimal> MAINTENANCE_STATUS { get; set; }
        public decimal MAINTENANCE_KOMTEK { get; set; }
    }
}
