//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_SNI_VALUATIONS
    {
        public decimal SNIVAL_ID { get; set; }
        public Nullable<decimal> SNIVAL_SOURCE_ID { get; set; }
        public string SNIVAL_CODE { get; set; }
        public string SNIVAL_NAME { get; set; }
        public string SNIVAL_IMAGE { get; set; }
        public Nullable<System.DateTime> SNIVAL_DATE { get; set; }
        public Nullable<decimal> SNIVAL_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SNIVAL_CREATE_DATE { get; set; }
        public Nullable<decimal> SNIVAL_STATUS { get; set; }
    }
}
