//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_SNI_SK_copy
    {
        public decimal SNI_SK_ID { get; set; }
        public Nullable<decimal> SNI_SK_SNI_ID { get; set; }
        public Nullable<decimal> SNI_SK_DOC_ID { get; set; }
        public string SNI_SK_NOMOR { get; set; }
        public Nullable<System.DateTime> SNI_SK_DATE { get; set; }
        public Nullable<System.DateTime> SNI_SK_CREATE_DATE { get; set; }
        public Nullable<decimal> SNI_SK_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SNI_SK_UPDATE_DATE { get; set; }
        public Nullable<decimal> SNI_SK_UPDATE_BY { get; set; }
        public Nullable<decimal> SNI_SK_STATUS { get; set; }
        public Nullable<System.DateTime> SNI_SK_DATE_START { get; set; }
        public Nullable<System.DateTime> SNI_SK_DATE_END { get; set; }
        public Nullable<decimal> JML_SNI { get; set; }
        public Nullable<decimal> IS_PUBLISH { get; set; }
        public string SNI_SK_KET { get; set; }
    }
}
