//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_MONITORING
    {
        public decimal MONITORING_ID { get; set; }
        public Nullable<decimal> MONITORING_PROPOSAL_ID { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_PNPS { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_PNPS { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_PNPS { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_MTPS { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_MTPS { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_MTPS { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RSNI1_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RSNI1_1 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RSNI1_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RATEK_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RATEK_1 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RATEK_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RATEK_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RATEK_2 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RATEK_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RATEK_3 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RATEK_3 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RATEK_3 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RATEK_4 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RATEK_4 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RATEK_4 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RATEK_5 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RATEK_5 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RATEK_5 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKON_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKON_1 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKON_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKON_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKON_2 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKON_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKON_3 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKON_3 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKON_3 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKON_4 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKON_4 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKON_4 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKON_5 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKON_5 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKON_5 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_AWAL_JP_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_AKHIR_JP_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_JP_1 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_JP_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_AWAL_JP_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_AKHIR_JP_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_JP_2 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_JP_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKOR_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKOR_1 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKOR_1 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKOR_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKOR_2 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKOR_2 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKOR_3 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKOR_3 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKOR_3 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKOR_4 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKOR_4 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKOR_4 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RAKOR_5 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RAKOR_5 { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RAKOR_5 { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_RASNI { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_RASNI { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_RASNI { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_PENETAPAN { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_PENETAPAN { get; set; }
        public Nullable<decimal> MONITORING_HASIL_APP_PENETAPAN { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_APP_PUB_PNPS { get; set; }
        public string MONITORING_NO_SRT_APP_PUB_PNPS { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_MEMO_KAPUS { get; set; }
        public Nullable<System.DateTime> MONITORING_TGL_MEMO_DEPUTI { get; set; }
        public string MONITORING_NO_MEMO_KAPUS { get; set; }
        public string MONITORING_NO_MEMO_DEPUTI { get; set; }
    }
}
