//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_PROPOSAL_ICS_REF
    {
        public decimal PROPOSAL_ICS_REF_ID { get; set; }
        public Nullable<decimal> PROPOSAL_ICS_REF_PROPOSAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_ICS_REF_ICS_ID { get; set; }
    }
}
