//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_LPK_DETAIL
    {
        public decimal LPK_LINGKUP_ID { get; set; }
        public Nullable<decimal> LPK_LINGKUP_LPK_ID { get; set; }
        public Nullable<decimal> LPK_LINGKUP_ICS_ID { get; set; }
        public Nullable<decimal> LPK_LINGKUP_CREATE_BY { get; set; }
        public Nullable<System.DateTime> LPK_LINGKUP_CREATE_DATE { get; set; }
        public Nullable<decimal> LPK_LINGKUP_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> LPK_LINGKUP_UPDATE_DATE { get; set; }
        public string LPK_LINGKUP_KETERANGAN { get; set; }
        public Nullable<decimal> LPK_LINGKUP_STATUS { get; set; }
    }
}
