//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_REGULASI_TEKNIS
    {
        public decimal RETEK_ID { get; set; }
        public string RETEK_NO_SK { get; set; }
        public string RETEK_TENTANG { get; set; }
        public Nullable<decimal> RETEK_REGULATOR { get; set; }
        public Nullable<decimal> RETEK_CREATE_BY { get; set; }
        public Nullable<System.DateTime> RETEK_CREATE_DATE { get; set; }
        public Nullable<decimal> RETEK_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> RETEK_UPDATE_DATE { get; set; }
        public Nullable<decimal> RETEK_STATUS { get; set; }
        public string RETEK_KETERANGAN { get; set; }
        public Nullable<decimal> RETEK_FILE { get; set; }
    }
}
