//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_REGTEK
    {
        public decimal RETEK_ID { get; set; }
        public string RETEK_NO_SK { get; set; }
        public string RETEK_TENTANG { get; set; }
        public Nullable<decimal> RETEK_REGULATOR { get; set; }
        public Nullable<decimal> RETEK_CREATE_BY { get; set; }
        public Nullable<System.DateTime> RETEK_CREATE_DATE { get; set; }
        public Nullable<decimal> RETEK_STATUS { get; set; }
        public string RETEK_KETERANGAN { get; set; }
        public Nullable<decimal> RETEK_FILE { get; set; }
        public string INSTANSI_CODE { get; set; }
        public string REGULATOR { get; set; }
        public Nullable<decimal> DOC_ID { get; set; }
        public Nullable<decimal> DOC_FOLDER_ID { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_DESCRIPTION { get; set; }
        public string DOC_FILE_PATH { get; set; }
        public string DOC_FILE_NAME { get; set; }
        public string DOC_FILETYPE { get; set; }
    }
}
