//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_PROPOSAL_RAPAT
    {
        public decimal PROPOSAL_RAPAT_ID { get; set; }
        public Nullable<decimal> PROPOSAL_RAPAT_PROPOSAL_ID { get; set; }
        public string PROPOSAL_RAPAT_NOMOR { get; set; }
        public Nullable<System.DateTime> PROPOSAL_RAPAT_DATE { get; set; }
        public Nullable<decimal> PROPOSAL_RAPAT_VERSION { get; set; }
        public Nullable<decimal> PROPOSAL_RAPAT_PROPOSAL_STATUS { get; set; }
        public Nullable<decimal> PROPOSAL_RAPAT_APPROVAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_RAPAT_DOC_ID { get; set; }
        public string PROPOSAL_RAPAT_STATUS_APPROVAL { get; set; }
    }
}
