//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_LPK
    {
        public decimal LPK_ID { get; set; }
        public string LPK_NAMA { get; set; }
        public string LPK_NOMOR { get; set; }
        public string LPK_LINGKUP { get; set; }
        public string LPK_LINGKUP_DETAIL { get; set; }
        public string LPK_ALAMAT { get; set; }
        public string LPK_TELEPON { get; set; }
        public string LPK_WEBSITE { get; set; }
        public string LPK_EMAIL { get; set; }
        public string LPK_CONTACT_PERSON { get; set; }
        public Nullable<System.DateTime> LPK_PERIODE_AWAL { get; set; }
        public string LPK_PERIODE_AWAL_DATE_NUMBER { get; set; }
        public Nullable<System.DateTime> LPK_PERIODE_AKHIR { get; set; }
        public string LPK_PERIODE_AKHIR_DATE_NUMBER { get; set; }
        public string LPK_KETERANGAN { get; set; }
        public string LPK_LAMPIRAN { get; set; }
        public Nullable<decimal> LPK_KATEGORI { get; set; }
        public string LPK_KATEGORI_NAMA { get; set; }
        public string LPK_FAX { get; set; }
        public Nullable<decimal> LPK_JENIS { get; set; }
        public string LPK_JENIS_NAMA { get; set; }
        public Nullable<decimal> LPK_SERTIFIKASI { get; set; }
        public Nullable<decimal> LPK_CREATE_BY { get; set; }
        public Nullable<System.DateTime> LPK_CREATE_DATE { get; set; }
        public Nullable<decimal> LPK_STATUS { get; set; }
        public string LPK_KODE_POS { get; set; }
        public Nullable<decimal> LPK_PROVINSI { get; set; }
        public Nullable<decimal> LPK_KABUPATENKOTA { get; set; }
        public string LPK_LINGKUP_NAME { get; set; }
        public Nullable<decimal> JML_SNI { get; set; }
    }
}
