//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DOCUMENTS
    {
        public decimal DOC_ID { get; set; }
        public string DOC_CODE { get; set; }
        public Nullable<decimal> DOC_FOLDER_ID { get; set; }
        public string DOC_FILE_PATH { get; set; }
        public string DOC_FILE_NAME { get; set; }
        public string DOC_FILETYPE { get; set; }
        public string DOC_FILETYPE_ICON { get; set; }
        public string DOC_FILETYPE_NAME { get; set; }
        public Nullable<decimal> DOC_RELATED_TYPE { get; set; }
        public string DOC_RELATED_TYPE_NAME { get; set; }
        public Nullable<decimal> DOC_RELATED_ID { get; set; }
        public Nullable<decimal> DOC_CREATE_TYPE { get; set; }
        public Nullable<decimal> DOC_EDITABLE { get; set; }
        public Nullable<decimal> DOC_DELETABLE { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_NAME_LOWER { get; set; }
        public string DOC_DESCRIPTION { get; set; }
        public Nullable<decimal> DOC_STATUS { get; set; }
        public Nullable<decimal> DOC_IS_XML { get; set; }
        public string DOC_XML_DATA { get; set; }
        public decimal DOC_CREATE_USER_ID { get; set; }
        public string DOC_CREATE_USER_NAME { get; set; }
        public string DOC_CREATE_NAME { get; set; }
        public Nullable<decimal> DOC_PROPOSAL_KOMTEK_ID { get; set; }
        public Nullable<decimal> DOC_SNI_KOMTEK_ID { get; set; }
        public string DOC_DATE { get; set; }
    }
}
