//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_USERS_PUBLIC
    {
        public decimal USER_ID { get; set; }
        public Nullable<decimal> USER_ACCESS_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public Nullable<decimal> USER_IS_ONLINE { get; set; }
        public Nullable<decimal> USER_STATUS { get; set; }
        public string ACCESS_NAME { get; set; }
        public decimal ACCESS_ID { get; set; }
        public Nullable<decimal> ACCESS_STATUS { get; set; }
        public decimal USER_PUBLIC_ID { get; set; }
        public string USER_PUBLIC_KTPSIM { get; set; }
        public string USER_PUBLIC_NOKK { get; set; }
        public string USER_PUBLIC_NAMA_LENGKAP { get; set; }
        public string USER_PUBLIC_EMAIL { get; set; }
        public string USER_PUBLIC_TELPON { get; set; }
        public Nullable<decimal> USER_PUBLIC_STAKEHOLDER { get; set; }
        public Nullable<decimal> USER_PUBLIC_KOTAKAB_ID { get; set; }
        public Nullable<decimal> USER_PUBLIC_PROVINSI_ID { get; set; }
        public string USER_PUBLIC_LINK_ACTIVATION { get; set; }
        public string USER_PUBLIC_ACTIVATION_KEY { get; set; }
    }
}
