//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SUBKOMTEK
    {
        public decimal KOMTEK_ID { get; set; }
        public string KOMTEK_PARENT_CODE { get; set; }
        public string SUB_KOMTEK { get; set; }
        public string PARENT_NAME { get; set; }
        public string KOMTEK_SEKRETARIAT { get; set; }
        public string KOMTEK_ADDRESS { get; set; }
        public Nullable<decimal> KOMTEK_BIDANG_ID { get; set; }
        public Nullable<decimal> KOMTEK_INSTANSI_ID { get; set; }
        public string KOMTEK_PHONE { get; set; }
        public string KOMTEK_FAX { get; set; }
        public string KOMTEK_EMAIL { get; set; }
        public string KOMTEK_SK_PENETAPAN { get; set; }
        public Nullable<System.DateTime> KOMTEK_TANGGAL_PEMBENTUKAN { get; set; }
        public string KOMTEK_DESCRIPTION { get; set; }
        public Nullable<decimal> KOMTEK_CREATE_BY { get; set; }
        public Nullable<System.DateTime> KOMTEK_CREATE_DATE { get; set; }
        public Nullable<decimal> KOMTEK_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> KOMTEK_UPDATE_DATE { get; set; }
        public Nullable<decimal> KOMTEK_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> KOMTEK_APPROVE_DATE { get; set; }
        public Nullable<decimal> KOMTEK_STATUS { get; set; }
        public string KOMTEK_LOG_CODE { get; set; }
        public string SUB_KOMTEK_CODE { get; set; }
        public Nullable<decimal> KOMTEK_TEMP_ID { get; set; }
        public string KOMTEK_CONTACT_PERSON { get; set; }
        public string KOMTEK_KETERANGAN { get; set; }
        public string KOMTEK_CV { get; set; }
        public string KOMTEK_CODE { get; set; }
        public string KOMTEK { get; set; }
        public string T_KOMTEK_ATTACHMENT { get; set; }
        public string BIDANG_NAME { get; set; }
        public string BIDANG_CODE { get; set; }
        public string INSTANSI_CODE { get; set; }
        public string INSTANSI_NAME { get; set; }
        public string KOMTEK_LINGKUP { get; set; }
    }
}
