//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_EMAIL_USER
    {
        public decimal KOMTEK_ANGGOTA_ID { get; set; }
        public string KOMTEK_CODE { get; set; }
        public string NOMOR { get; set; }
    }
}
