//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_PEMELIHARAAN
    {
        public decimal MAINTENANCE_DETAIL_ID { get; set; }
        public Nullable<decimal> MAINTENANCE_DETAIL_MTN_ID { get; set; }
        public Nullable<decimal> MAINTENANCE_DETAIL_SNI_ID { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_DETAIL_REV_DATE { get; set; }
        public string MAINTENANCE_REV_DATE_TEXT { get; set; }
        public Nullable<decimal> MAINTENANCE_DETAIL_RESULT { get; set; }
        public string DETAIL_RESULT_TEXT { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_DETAIL_REPORT_DATE { get; set; }
        public string MAINTENANCE_REPORT_DATE_TEXT { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_DETAIL_USUL_DATE { get; set; }
        public string MAINTENANCE_USUL_DATE_TEXT { get; set; }
        public decimal MAINTENANCE_ID { get; set; }
        public string MAINTENANCE_DOC_NUMBER { get; set; }
        public Nullable<decimal> MAINTENANCE_REV_NUMBER { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_DATE { get; set; }
        public string MAINTENANCE_DATE_TEXT { get; set; }
        public Nullable<decimal> MAINTENANCE_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_CREATE_DATE { get; set; }
        public Nullable<decimal> MAINTENANCE_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MAINTENANCE_UPDATE_DATE { get; set; }
        public Nullable<decimal> MAINTENANCE_STATUS { get; set; }
        public string SNI_NOMOR { get; set; }
    }
}
