//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DOC_ACCESS
    {
        public decimal DOC_ACCESS_ID { get; set; }
        public string DOC_ACCESS_NAME { get; set; }
        public Nullable<decimal> DOC_ACCESS_CREATE_BY { get; set; }
        public Nullable<System.DateTime> DOC_ACCESS_CREATE_DATE { get; set; }
        public Nullable<decimal> DOC_ACCESS_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> DOC_ACCESS_UPDATE_DATE { get; set; }
        public Nullable<decimal> DOC_ACCESS_STATUS { get; set; }
        public Nullable<decimal> JML_ACCES { get; set; }
    }
}
