//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_RSNI_PORTAL
    {
        public string PROPOSAL_TYPE_NAME { get; set; }
        public string PROPOSAL_TAHAPAN { get; set; }
        public decimal PROPOSAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_YEAR { get; set; }
        public Nullable<decimal> PROPOSAL_KOMTEK_ID { get; set; }
        public string PROPOSAL_NO_SNI_PROPOSAL { get; set; }
        public string PROPOSAL_JUDUL_PNPS { get; set; }
        public string PROPOSAL_JUDUL_PNPS_ENG { get; set; }
        public Nullable<decimal> PROPOSAL_JENIS_PERUMUSAN { get; set; }
        public string PROPOSAL_JENIS_PERUMUSAN_NAME { get; set; }
        public string PROPOSAL_LAMPIRAN_FILE_PATH { get; set; }
        public string KOMTEK_CODE { get; set; }
        public string KOMTEK_NAME { get; set; }
        public string PROPOSAL_STATUS_NAME { get; set; }
        public string PROPOSAL_RUANG_LINGKUP { get; set; }
        public string PROPOSAL_RUANG_LINGKUP_ENG { get; set; }
        public string PROPOSAL_ICS { get; set; }
        public string PROPOSAL_ICS_NAME { get; set; }
    }
}
