//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_REKAP_SNI_BY_SK_DETAIL
    {
        public decimal SNI_SK_ID { get; set; }
        public string SNI_SK_NOMOR { get; set; }
        public Nullable<System.DateTime> SNI_SK_DATE { get; set; }
        public string SNI_SK_YEAR_NAME { get; set; }
        public Nullable<decimal> JML_SNI { get; set; }
        public decimal SNI_ID { get; set; }
        public string SNI_NOMOR { get; set; }
        public string SNI_JUDUL { get; set; }
        public Nullable<decimal> IS_MEREVISI { get; set; }
        public Nullable<decimal> IS_DIREVISI { get; set; }
        public Nullable<decimal> PROPOSAL_IS_BATAL { get; set; }
        public Nullable<decimal> PROPOSAL_JENIS_PERUMUSAN { get; set; }
    }
}
