//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_NOTIF
    {
        public decimal NOTIF_ID { get; set; }
        public Nullable<decimal> NOTIF_USER_ID { get; set; }
        public string NOTIF_LINK { get; set; }
        public string NOTIF_MESSAGE { get; set; }
        public Nullable<System.DateTime> NOTIF_DATE { get; set; }
        public Nullable<decimal> NOTIF_TYPE { get; set; }
        public string NOTIF_TYPE_NAME { get; set; }
        public Nullable<decimal> NOTIF_IS_FLASH { get; set; }
        public Nullable<decimal> NOTIF_IS_COUNT { get; set; }
        public Nullable<decimal> NOTIF_CATEGORY { get; set; }
        public string NOTIF_CATEGORY_NAME { get; set; }
        public Nullable<decimal> NOTIF_DATA_ID { get; set; }
        public Nullable<decimal> KOMTEK_ID { get; set; }
        public Nullable<decimal> KOMTEK_BIDANG_ID { get; set; }
        public Nullable<decimal> NOTIF_STATUS { get; set; }
    }
}
