//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MENUS
    {
        public decimal MENU_ID { get; set; }
        public Nullable<decimal> MENU_PARENT_ID { get; set; }
        public string MENU_NAME { get; set; }
        public Nullable<decimal> MENU_ANAK { get; set; }
        public Nullable<decimal> MENU_LEVEL { get; set; }
    }
}
