//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_REGTEK_DETAIL
    {
        public decimal RETEK_DETAIL_ID { get; set; }
        public Nullable<decimal> RETEK_DETAIL_RETEK_ID { get; set; }
        public Nullable<decimal> RETEK_DETAIL_SNI_ID { get; set; }
        public Nullable<decimal> RETEK_DETAIL_STATUS { get; set; }
        public string SNI_NOMOR { get; set; }
        public string SNI_JUDUL { get; set; }
        public Nullable<decimal> SNI_IS_PUBLISH { get; set; }
        public Nullable<decimal> SNI_TIDAK_BERLAKU { get; set; }
        public string DSNI_DOC_FILE_PATH { get; set; }
        public string DSNI_DOC_FILE_NAME { get; set; }
        public string SNI_SK_NOMOR { get; set; }
        public string DSNI_DOC_FILETYPE { get; set; }
        public string DSNI_DOC_LINK { get; set; }
    }
}
