//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_NEWS
    {
        public decimal NEWS_ID { get; set; }
        public string NEWS_TITLE { get; set; }
        public string NEWS_PATH_IMAGE { get; set; }
        public Nullable<decimal> NEWS_CREATE_BY { get; set; }
        public Nullable<System.DateTime> NEWS_CREATE_DATE { get; set; }
        public Nullable<decimal> NEWS_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> NEWS_UPDATE_DATE { get; set; }
        public Nullable<decimal> NEWS_STATUS { get; set; }
        public string NEWS_CONTENTS { get; set; }
        public string NEWS_SUMBER { get; set; }
        public string NEWS_BRIEF_NEWS { get; set; }
        public string NEWS_TAG { get; set; }
        public string NEWS_LINK_IMAGE { get; set; }
        public string USER_FULL_NAME { get; set; }
        public Nullable<decimal> USER_ACCESS_ID { get; set; }
        public string ACCESS_NAME { get; set; }
    }
}
