//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_POLLING_DETAIL
    {
        public decimal POLLING_DETAIL_ID { get; set; }
        public Nullable<decimal> POLLING_DETAIL_POLLING_ID { get; set; }
        public Nullable<decimal> POLLING_DETAIL_OPTION { get; set; }
        public string PILIHAN { get; set; }
        public string POLLING_DETAIL_REASON { get; set; }
        public Nullable<decimal> POLLING_DETAIL_INPUT_TYPE { get; set; }
        public Nullable<decimal> POLLING_DETAIL_IS_APPROVE { get; set; }
        public Nullable<decimal> POLLING_DETAIL_CREATE_BY { get; set; }
        public Nullable<System.DateTime> POLLING_DETAIL_CREATE_DATE { get; set; }
        public string POLLING_FULL_DATE_NAME { get; set; }
        public Nullable<decimal> POLLING_DETAIL_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> POLLING_DETAIL_APPROVE_DATE { get; set; }
        public Nullable<decimal> POLLING_DETAIL_STATUS { get; set; }
        public string POLLING_DETAIL_PASAL { get; set; }
        public string POLLING_DETAIL_FILE_PATH { get; set; }
        public Nullable<decimal> POLLING_PROPOSAL_ID { get; set; }
        public string POLLING_TYPE { get; set; }
        public Nullable<decimal> POLLING_VERSION { get; set; }
        public string USER_PUBLIC_NAMA_LENGKAP { get; set; }
        public string USER_PUBLIC_NAMA { get; set; }
        public string POLLING_DETAIL_INPUT_TYPE_NAME { get; set; }
    }
}
