//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MONITORING_RSNI
    {
        public decimal PROPOSAL_ID { get; set; }
        public string PROPOSAL_JUDUL_SNI_PROPOSAL { get; set; }
        public string MTPS { get; set; }
        public string PNPS { get; set; }
        public string RSNI1 { get; set; }
        public string RSNI2 { get; set; }
        public string RSNI3 { get; set; }
        public string RSNI4 { get; set; }
        public string RSNI5 { get; set; }
        public string RSNI6 { get; set; }
        public string RASNI { get; set; }
        public string SNI_TANGGAL_PENETAPAN { get; set; }
        public string TANGGAL_PUBLIKASI { get; set; }
        public string TANGGAL_UPLOAD_DOC { get; set; }
        public string TANGGAL_UPLOAD_PDF { get; set; }
    }
}
