//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_MASTER_TAS
    {
        public decimal TAS_ID { get; set; }
        public string TAS_NAME { get; set; }
        public Nullable<decimal> TAS_INSTANSI_ID { get; set; }
        public string TAS_ADDRESS { get; set; }
        public string TAS_PHONE { get; set; }
        public string TAS_FAX { get; set; }
        public string TAS_OFFICE_ADDRESS { get; set; }
        public string TAS_OFFICE_PHONE { get; set; }
        public string TAS_HANDPHONE { get; set; }
        public string TAS_EMAIL { get; set; }
        public Nullable<decimal> TAS_CREATE_BY { get; set; }
        public Nullable<System.DateTime> TAS_CREATE_DATE { get; set; }
        public Nullable<decimal> TAS_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> TAS_UPDATE_DATE { get; set; }
        public Nullable<decimal> TAS_STATUS { get; set; }
        public string TAS_LOG_CODE { get; set; }
        public string INSTANSI_CODE { get; set; }
        public string INSTANSI_NAME { get; set; }
    }
}
