//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_INSTANSI
    {
        public decimal INSTANSI_ID { get; set; }
        public string INSTANSI_CODE { get; set; }
        public string INSTANSI_NAME { get; set; }
        public Nullable<System.DateTime> INSTANSI_CREATE_DATE { get; set; }
        public Nullable<decimal> INSTANSI_CREATE_BY { get; set; }
        public Nullable<System.DateTime> INSTANSI_APPROVE_DATE { get; set; }
        public Nullable<decimal> INSTANSI_APPROVE_BY { get; set; }
        public string INSTANSI_LOG_CODE { get; set; }
        public Nullable<decimal> INSTANSI_STATUS { get; set; }
    }
}
