//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_KOMTEK_ICS
    {
        public Nullable<decimal> KOMTEK_ICS_ICS_ID { get; set; }
        public decimal KOMTEK_ICS_ID { get; set; }
        public Nullable<decimal> KOMTEK_ICS_KOMTEK_ID { get; set; }
        public Nullable<decimal> KOMTEK_ICS_CREATE_BY { get; set; }
        public Nullable<System.DateTime> KOMTEK_ICS_CREATE_DATE { get; set; }
        public Nullable<decimal> KOMTEK_ICS_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> KOMTEK_ICS_UPDATE_DATE { get; set; }
        public Nullable<decimal> KOMTEK_ICS_STATUS { get; set; }
        public string ICS_CODE { get; set; }
        public string ICS_NAME { get; set; }
        public string ICS_NAME_IND { get; set; }
        public string ICS_YEAR { get; set; }
        public string KOMTEK_ICS_LOG_CODE { get; set; }
    }
}
