//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SK_PER_SNI
    {
        public decimal SNI_SK_ID { get; set; }
        public Nullable<decimal> SNI_SK_SNI_ID { get; set; }
        public Nullable<decimal> SNI_SK_DOC_ID { get; set; }
        public string SNI_SK_NOMOR { get; set; }
        public Nullable<System.DateTime> SNI_SK_DATE { get; set; }
        public string SNI_SK_DATE_NAME { get; set; }
        public Nullable<System.DateTime> SNI_SK_CREATE_DATE { get; set; }
        public Nullable<decimal> SNI_SK_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SNI_SK_DATE_START { get; set; }
        public string SNI_SK_DATE_START_NAME { get; set; }
        public Nullable<System.DateTime> SNI_SK_DATE_END { get; set; }
        public string SNI_SK_DATE_END_NAME { get; set; }
        public Nullable<decimal> JML_SNI { get; set; }
        public Nullable<decimal> IS_PUBLISH { get; set; }
        public string SNI_SK_KET { get; set; }
        public decimal DOC_ID { get; set; }
        public string DOC_CODE { get; set; }
        public Nullable<decimal> DOC_FOLDER_ID { get; set; }
        public string DOC_NUMBER { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_FILE_PATH { get; set; }
        public string DOC_FILE_NAME { get; set; }
        public string DOC_FILETYPE { get; set; }
        public string DOC_LINK { get; set; }
        public decimal SNI_ID { get; set; }
        public Nullable<decimal> SNI_PROPOSAL_ID { get; set; }
        public Nullable<decimal> SNI_DOC_ID { get; set; }
        public Nullable<System.DateTime> SNI_CREATE_DATE { get; set; }
        public Nullable<decimal> SNI_CREATE_BY { get; set; }
        public Nullable<System.DateTime> SNI_UPDATE_DATE { get; set; }
        public Nullable<decimal> SNI_UPDATE_BY { get; set; }
        public Nullable<decimal> SNI_STATUS { get; set; }
        public string SNI_NOMOR { get; set; }
        public string SNI_JUDUL { get; set; }
        public Nullable<decimal> SNI_IS_PUBLISH { get; set; }
        public Nullable<System.DateTime> SNI_PUBLISH_START_DATE { get; set; }
        public Nullable<System.DateTime> SNI_PUBLISH_END_DATE { get; set; }
        public Nullable<decimal> SNI_TIDAK_BERLAKU { get; set; }
        public string SNI_JUDUL_ENG { get; set; }
    }
}
