//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_LOG
    {
        public long LOG_ID { get; set; }
        public string LOGNAME { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
    }
}
