//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ANGGOTA
    {
        public decimal KOMTEK_ANGGOTA_ID { get; set; }
        public Nullable<decimal> KOMTEK_ANGGOTA_KOMTEK_ID { get; set; }
        public Nullable<decimal> KOMTEK_ANGGOTA_KODE { get; set; }
        public string KOMTEK_ANGGOTA_NAMA { get; set; }
        public Nullable<decimal> KOMTEK_ANGGOTA_JABATAN { get; set; }
        public string KOMTEK_ANGGOTA_INSTANSI { get; set; }
        public string KOMTEK_ANGGOTA_ADDRESS { get; set; }
        public string KOMTEK_ANGGOTA_TELP { get; set; }
        public string KOMTEK_ANGGOTA_FAX { get; set; }
        public string KOMTEK_ANGGOTA_EMAIL { get; set; }
        public string KOMTEK_ANGGOTA_STAKEHOLDER { get; set; }
        public Nullable<decimal> KOMTEK_ANGGOTA_EDUCATION { get; set; }
        public string KOMTEK_ANGGOTA_EXPERTISE { get; set; }
        public Nullable<decimal> KOMTEK_ANGGOTA_CREATE_BY { get; set; }
        public Nullable<System.DateTime> KOMTEK_ANGGOTA_DATE { get; set; }
        public Nullable<decimal> KOMTEK_ANGGOTA_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> KOMTEK_ANGGOTA_UPDATE_DATE { get; set; }
        public Nullable<decimal> KOMTEK_ANGGOTA_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> KOMTEK_ANGGOTA_APPROVE_DATE { get; set; }
        public Nullable<decimal> KOMTEK_ANGGOTA_STATUS { get; set; }
        public string KOMTEK_ANGGOTA_LOG_CODE { get; set; }
        public string KOMTEK_CODE { get; set; }
        public string KOMTEK_PARENT_CODE { get; set; }
        public string KOMTEK_NAME { get; set; }
        public string KOMTEK_SK_PENETAPAN { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string JABATAN { get; set; }
        public string PENDIDIKAN { get; set; }
        public string STAKEHOLDER { get; set; }
    }
}
