//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SNI_ADOPSI_PORTAL
    {
        public Nullable<decimal> PROPOSAL_ADOPSI_PROPOSAL_ID { get; set; }
        public Nullable<decimal> PROPOSAL_ADOPSI_TYPE { get; set; }
        public decimal SNI_ID { get; set; }
        public string SNI_NOMOR { get; set; }
        public string SNI_JUDUL { get; set; }
        public Nullable<decimal> SNI_TIDAK_BERLAKU { get; set; }
        public string PROPOSAL_ADOPSI_NOMOR_JUDUL { get; set; }
    }
}
