//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_REKAP_SNI_BY_ICS
    {
        public decimal ICS_ID { get; set; }
        public string ICS_CODE { get; set; }
        public string ICS_NAME { get; set; }
        public string ICS_YEAR { get; set; }
        public string ICS_NAME_IND { get; set; }
        public Nullable<decimal> JML_PNPS { get; set; }
        public Nullable<decimal> JML_RSNI1 { get; set; }
        public Nullable<decimal> JML_RSNI2 { get; set; }
        public Nullable<decimal> JML_RSNI3 { get; set; }
        public Nullable<decimal> JML_RSNI4 { get; set; }
        public Nullable<decimal> JML_RSNI5 { get; set; }
        public Nullable<decimal> JML_RASNI { get; set; }
        public Nullable<decimal> JML_SNI { get; set; }
    }
}
