//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ANOR_STANDAR_ASING
    {
        public Nullable<decimal> PROPOSAL_REF_PROPOSAL_ID { get; set; }
        public decimal SNI_ID { get; set; }
        public string SNI_NOMOR { get; set; }
        public string SNI_JUDUL { get; set; }
        public Nullable<decimal> SNI_TIDAK_BERLAKU { get; set; }
        public string SNI_ID_ACUAN_NORMATIF { get; set; }
    }
}
