//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_WILAYAH_PROVINSI
    {
        public decimal WILAYAH_ID { get; set; }
        public Nullable<decimal> WILAYAH_PARENT_ID { get; set; }
        public string WILAYAH_NAMA { get; set; }
        public Nullable<decimal> WILAYAH_STATUS { get; set; }
    }
}
