//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ACCESS
    {
        public decimal ACCESS_ID { get; set; }
        public string ACCESS_NAME { get; set; }
        public Nullable<decimal> ACCESS_DEFAULT_MENU { get; set; }
        public Nullable<decimal> ACCESS_CREATE_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_CREATE_DATE { get; set; }
        public Nullable<decimal> ACCESS_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> ACCESS_UPDATE_DATE { get; set; }
        public Nullable<decimal> ACCESS_STATUS { get; set; }
        public string ACCESS_LOG_CODE { get; set; }
        public Nullable<decimal> JML_PENGGUNA { get; set; }
    }
}
