//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_T_KOMTEK
    {
        public decimal T_KOMTEK_ID { get; set; }
        public string T_KOMTEK_PARENT_CODE { get; set; }
        public string PARENT_NAME { get; set; }
        public Nullable<decimal> T_KOMTEK_BIDANG_ID { get; set; }
        public Nullable<decimal> T_KOMTEK_INSTANSI_ID { get; set; }
        public Nullable<decimal> T_KOMTEK_ICS_ID { get; set; }
        public string T_KOMTEK_NAME { get; set; }
        public string T_KOMTEK_SEKRETARIAT { get; set; }
        public string T_KOMTEK_ADDRESS { get; set; }
        public string T_KOMTEK_CODE { get; set; }
        public string T_KOMTEK_PHONE { get; set; }
        public string T_KOMTEK_FAX { get; set; }
        public string T_KOMTEK_EMAIL { get; set; }
        public string T_KOMTEK_SK_PENETAPAN { get; set; }
        public Nullable<System.DateTime> T_KOMTEK_TANGGAL_PEMBENTUKAN { get; set; }
        public string T_KOMTEK_DESCRIPTION { get; set; }
        public Nullable<decimal> T_KOMTEK_CREATE_BY { get; set; }
        public Nullable<System.DateTime> T_KOMTEK_CREATE_DATE { get; set; }
        public Nullable<decimal> T_KOMTEK_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> T_KOMTEK_UPDATE_DATE { get; set; }
        public Nullable<decimal> T_KOMTEK_APPROVE_BY { get; set; }
        public Nullable<System.DateTime> T_KOMTEK_APPROVE_DATE { get; set; }
        public Nullable<decimal> T_KOMTEK_STATUS { get; set; }
        public string T_KOMTEK_LOG_CODE { get; set; }
        public string T_KOMTEK_ATTACHMENT { get; set; }
        public string BIDANG_CODE { get; set; }
        public string BIDANG_NAME { get; set; }
        public string INSTANSI_CODE { get; set; }
        public string INSTANSI_NAME { get; set; }
    }
}
