//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISPK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TAS_DETAIL_ICS
    {
        public decimal TAS_DETAIL_ICS_ID { get; set; }
        public Nullable<decimal> TAS_DETAIL_ICS_TAS_ID { get; set; }
        public Nullable<decimal> TAS_DETAIL_ICS_ICS_ID { get; set; }
        public Nullable<decimal> TAS_DETAIL_ICS_STATUS { get; set; }
        public string ICS_CODE { get; set; }
        public string ICS_NAME { get; set; }
        public string ICS_YEAR { get; set; }
        public string ICS_NAME_IND { get; set; }
    }
}
